name: CI
on:
  push:
  workflow_dispatch:

jobs:
  validate-openapi:
    name: Validate OpenAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate openapi.yaml
        run: make validate_openapi
